 ### Importing numpy

In [1]:
import numpy as np

#### Basics

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


#### Built-in functions

In [4]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
#  get shape 
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# get type
print(a.dtype)
print(b.dtype)

int64
float64


In [7]:
# get size
print(a.itemsize)
print(b.itemsize)

8
8


In [8]:
# total size
print(a.size * a.itemsize)
print(a.nbytes)

print(b.size * b.itemsize)
print(b.nbytes)

24
24
48
48


#### Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
# get specific element [r, c]
print(a[1, 2])
print(a[0, -3])

7
2


In [11]:
#  get a specific row
print(a[0, :])

[1 2 3 4]


In [12]:
# get a specific column
print(a[:, 2])

[3 7]


In [13]:
# getting from [start_index:end_index:step_size]
print(a[0, 1:3])
# here first element of a is included from index 1 to 2 (3 is excluded)

[2 3]


In [14]:
# replace a specific element
a[1, 2] = 20
print(a)

[[ 1  2  3  4]
 [ 5  6 20  8]]


In [15]:
#  replace row
a[:, 2] = [1, 2]
print(a)

[[1 2 1 4]
 [5 6 2 8]]


In [16]:
#  replace column
a[1, :] = [9,8,7,6]
print(a)

[[1 2 1 4]
 [9 8 7 6]]


#### Arrays

In [17]:
# all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# all ones matrix
np.ones((4,2,2), dtype='str')

array([[['1', '1'],
        ['1', '1']],

       [['1', '1'],
        ['1', '1']],

       [['1', '1'],
        ['1', '1']],

       [['1', '1'],
        ['1', '1']]], dtype='<U1')

In [19]:
# any other number
np.full((2,2), 99)
# syntax: np.full((shape), number)

array([[99, 99],
       [99, 99]])

In [20]:
# full like 
np.full_like(a, 4)
# takes the shape of a and fills it with 4

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [21]:
# random decimal numbers
np.random.rand(3,2)

array([[0.74696384, 0.88297091],
       [0.24598563, 0.29638835],
       [0.72049935, 0.62814263]])

In [22]:
# from shape of prev array
np.random.random_sample(a.shape)

array([[0.27190972, 0.98985159, 0.86862286, 0.04270833],
       [0.32577436, 0.53903474, 0.40849112, 0.65630024]])

In [23]:
# random integer values
np.random.randint(-4,8, size=(3,3))
# syntax: np.random.randint(start_range, end_range, size=(shape))

array([[ 6, -3,  3],
       [ 7, -4, -1],
       [ 4,  3, -1]])

In [24]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# repeat an array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
# syntax: np.repeat(array, number_of_times, axis)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Question 1
![image.png](./assets/q1.png)

In [26]:
# creating a ones matrix 5x5
op = np.ones((5,5))
# print(op)

# creating a zeros matrix 3x3
z = np.zeros((3,3))
# print(z)
# set the middle element to 9
z[1,1] = 9
# print(z)

# set the middle element of op to z
op[1:4, 1:4] = z
print(op)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Copying arrays

In [27]:
a = np.array([1,2,3])
print(a)
b = a

[1 2 3]


In [28]:
b[0] = 100
print(a) # altering b, a is also changed
print(b)

[100   2   3]
[100   2   3]


In [29]:
# use copy to avoid this
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


#### Mathematics

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a + 2

array([3, 4, 5, 6])

In [32]:
a - 2

array([-1,  0,  1,  2])

In [33]:
b = np.array([1,0,1,3])
a + b

array([2, 2, 4, 7])

In [34]:
b ** 2

array([1, 0, 1, 9])

In [35]:
# can also take the sin, cos, tan, etc
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear algebra

In [36]:
# initialize 2D arrays
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [37]:
# multiply a and b
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [38]:
# determinant of a matrix
c = np.identity(3)
np.linalg.det(c)
# linalg: linear algebra dot determinant (acronym)

1.0

In [39]:
#  other reference docs
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

#### Statistics

In [40]:
stats = np.array([[1,2,3], [4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [41]:
# min
np.min(stats,axis=1)

array([1, 4])

In [42]:
# max 
np.max(stats,axis=0)

array([4, 5, 6])

In [43]:
# sum
np.sum(stats)

21

#### Reorganizing arrays

In [44]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print("Shape:"+ str(before.shape))

[[1 2 3 4]
 [5 6 7 8]]
Shape:(2, 4)


In [45]:
after = before.reshape((8,1))
print(after)
print("Shape:"+ str(after.shape))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Shape:(8, 1)


In [46]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
# horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

In [48]:
# load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [49]:
# advanced indexing and boolean masking
print(filedata > 50)
# returns a boolean array with True where the condition is met

print(filedata[filedata > 50])
# returns an array with values where the condition is met

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[196  75 766  75  55 999  78  76  88]


In [50]:
# count the number of values greater than 50
print(np.sum(filedata > 50))

9


In [51]:
# you can also do this row wise or column wise
print(np.any(filedata > 50, axis=0))
print(np.sum(filedata > 50, axis=0))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[0 0 0 0 3 2 0 1 1 0 0 0 0 0 0 0 1 1]


In [52]:
# check if all values are greater than 50 
print(np.all(filedata > 50, axis=0))

[False False False False  True False False False False False False False
 False False False False False False]


In [53]:
# using the & and | operators
print((filedata > 50) & (filedata < 100))
print((filedata > 50) | (filedata < 100))

[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]]


#### Question 2 a
Index the given part of array

![image.png](./assets/q2a.png)

In [54]:
m = np.arange(1,31).reshape(6,5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [55]:
a = m[2:4, 0:2]
print(a)

[[11 12]
 [16 17]]


#### Question 2 b
Index the given part of array

![image.png](./assets/q2b.png)

In [56]:
b = m[[0,1,2,3], [1,2,3,4]]
print(b)

[ 2  8 14 20]


#### Question 2 c
Index the given part of array

![image.png](./assets/q2c.png)

In [57]:
c = m[[0,4,5], 3:]
print(c)

[[ 4  5]
 [24 25]
 [29 30]]
